modLoader="javafml"

loaderVersion="[32,)"

#issueTrackerURL="https://github.com/Afroduckie/WillWarchest/issues" #optional

[[mods]]

modId="agwarchest"

version="0.1.0"

displayName="William's Warchest"

#updateJSONURL="null"

#displayURL="" #optional

#logoFile="" #optional

#credits="Update Later"

authors="AndrielGaming William"

description='''
"One of everything, please!"

William's Warchest is a collection of additions to vanilla gameplay. New items, blocks, enchantments, ores, mobs, biomes, structures, and even a new boss are added with an aim to make survival mode
a more engaging and dynamic experience full of surprises, twists, and turns! Please refer to the issues page, wiki, or suggestion menu if you have any associated feedback to give!
'''


#Dependencies
[[dependencies.agwarchest]]
    modId="forge" 
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.agwarchest]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
